# Generated by Django 4.2.5 on 2024-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email_trainer', models.EmailField(max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('dob', models.DateField(default='2000-01-01')),
                ('contact_no', models.CharField(default=False, max_length=20)),
                ('state', models.CharField(default='New Delhi', max_length=50)),
                ('domain', models.CharField(choices=[('Yoga Trainer', 'Yoga Trainer'), ('Fitness Trainer', 'Fitness Trainer'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Dietitian', 'Dietitian'), ('Nutritionist', 'Nutritionist'), ('Sujok Trainer', 'Sujok Trainer'), ('Special Population', 'Special Population'), ('Rehabilitation', 'Rehabilitation'), ('Coach', 'Coach'), ('Athlete', 'Athlete'), ('Resource', 'Resource'), ('Academy', 'Academy'), ('Gym', 'Gym'), ('Other', 'Other')], default='other', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='trainer_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='trainer_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
