# Generated by Django 4.2.5 on 2024-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='email_trainer',
            new_name='email',
        ),
    ]
