# Generated by Django 4.2.5 on 2024-07-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_email_trainer_trainer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='session_token',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
